### ISSUE TITLE
How to create fiducial file

### ISSUE THREAD

**Issue by neuronium** [mnarizzano/SEEGA#112]
Hello
I am a neurosurgeon who is using brainlab for seeg electrode locations just by manually entering coordinates according to AC-PC
I am looking for different Seeg analyzers to make my life easier and get automatic segmentation. So far tried YAEL and it was easy to use. But I am also trying to learn and compare SEEGA.
My problem is I am trying to figure out do I definitely need a fiducial file and give 3D slicer exact coordinates of entry and target of electrodes? That kind of defies the purpose for me. I am already trying to bypass that level.
Is there any way to bypass that step? Let SEEGA automatically define electrode locations?

If not, can someone share a sample fcsv file so I can see the format that I should prepare. 

Thanks

**Comment by gabri470** [comment]
Hi

Sorry for the late reply.

The fiducial file is a simple file listing entry and target point of each electrode. Currently that step is mandatory and cannot be bypassed. Based on the information contained in the fiducial file, the final coordinates are associated with the correct labels.

You can create a fiducial list directly using 3DSlicer interface by adding fiducial point for individual entry and target points.

Check the video tutorial in the official documentation of this repository. 

Let us know if you encounter any problem with the tool or in case you need additional support.

Best 

Gabriele
