### ISSUE TITLE
ERROR: electrode misplaced 

### ISSUE THREAD

**Issue by emilykubota** [mnarizzano/SEEGA#113]
Hello, I removed the skull from my images and created a markups fiducial file however whenever I try to "Start Segmentation" I get "ERROR: electrode misplaced". Is the software looking for alignment between the coordinates in the markups fiducial file and the bright intensities in the image? From my understanding, an ideal CT volume would be an image with white electrodes with everything else in the image black? I tried to create a more simple version with a single electrode with matching coordinates in the markups fiducial file, and am still getting the same error.

**Comment by gabri470** [comment]
Hello, can you please provide me with an image of the Interface showing where you placed the cortical entry and target points in respect to the CT?

If you possibly share the original file it with us it would make easier for us to track down your specific problem.

Thanks a lot

**Comment by emilykubota** [comment]
Yes, here is an image showing the cleaned CT with the entry and target points and the original files on [google drive](https://drive.google.com/drive/folders/1KcQIFIo-r-OGSX54q85aMoj2sOrjqFD-?usp=sharing).
![Screenshot 2024-08-13 at 5 17 26 PM](https://github.com/user-attachments/assets/0287de3d-1639-4434-99f4-b2bf23bff736)

**Comment by gabri470** [comment]
Dear @emilykubota sorry, I forgot about this. I'm gonna look into this issue with your data and see if I can reproduce it and find a fix for your case.

Best regards, 

Gabriele

**Comment by emilykubota** [comment]
We just resolved this issue yesterday! The points were slightly off. Closing the issue!

**Comment by emilykubota** [comment]
Points from robot were slightly off.
