### ISSUE TITLE
CPE error: electrode misplaced

### ISSUE THREAD

**Issue by yuanci89** [mnarizzano/SEEGA#114]
I'm running into an error with CPE where it's not able to segment the leads giving me an error "electrode misplaced"... Unsure if I'm missing a step, I have 14 leads here.
![Capture](https://github.com/user-attachments/assets/09fa4633-df52-4c66-b27b-1c2b9d278482)

**Comment by mnarizzano** [comment]
Dear Yuanci89,
1) you should have 14 electrodes, but CPE shows only 9
2) The first one does not have a proper name,  that could be a problem 
Try to segment one at the time, it may give you some hint in which is the electrode that cause error. 
Otherwise send me the files and I will try to replicate your error.

**Comment by yuanci89** [comment]
Hi!

I tinkered with it a little more late last night and figured it out. I was previously numbering the electrodes, but for whatever reason, it didn't recognize the two-digit numbers. Once I named the entry/target points by letter instead, and it worked.

Thanks

**Comment by yuanci89** [comment]
Actually, I ran the process on a different patient and I'm running into the error again. My CT (original and post-processed) and markup file: https://www.dropbox.com/scl/fi/hdz5h6xh6rvir1etypnhs/electrode-misplaced.zip?rlkey=7hnxg4np134ghjvgstgb3y4ow&st=euxfgesr&dl=0
Unfortunately the top part of the CT was lost before it sent to PACS but it does have almost all the leads included, except the orbitofrontal one but all the relevant contact points are included.
![image](https://github.com/user-attachments/assets/bc2d65d2-6b0d-4278-aff1-646726eee3d5)

**Comment by mnarizzano** [comment]
Dear Yuanci89,
one of the difficulties in reconstruction is to find the target and entry points (TP cEP)
If this fails (electrode misplaced) the electrode can not be reconstructed. But if you trust your entry and target point then you can add a flag on TP and cPE right to the electrode name in CPE module, and that can help. Indeed I downloaded your datas and reconstructed the ROF just by adding the flag cPE.  
![image](https://github.com/user-attachments/assets/cd988881-5fc4-4147-a48c-9e0af9184f7e)

As a last remark 
look at the type/model of your electrode. All types of electrodes are estimated by CPE, and it may do it  wrong.  So for example all your electrodes are of type D08-12AM while ROF and the RPC are D08-18AM and thats looks strange to me.

**Comment by yuanci89** [comment]
Thank you!

I added cEP for the missing electrodes and it worked! So ROF and RPC are longer leads, and RTP is actually a shorter lead... on first glance the contact points look correct to me!

![image](https://github.com/user-attachments/assets/207b0c22-884b-4f71-8844-e603a126338d)
