### ISSUE TITLE
update FiducialList without requiring update of ElectrodeTable

### ISSUE THREAD

**Issue by gabri470** [mnarizzano/SEEGA#24]
currently if one changes a single fiducial, its value is not changed in CPE until a full reload of ElectrodeTable. One the other hand, if one has defined/select configurations different from the standard (proposed automatically by CPE) those changes are lost reloading the table.

**Comment by abiii-daniele** [comment]
28e6244
I added a list variable that takes into account the last electrodes, where the electrodes will be added when the file is loaded.
When the update button is pressed, in addition to detecting the location of the new electrodes, the list will update itself by removing the old ones and adding the new ones.
Finally, the graphics in the Slicer will remain static and only backend will be updated without reloading
