### ISSUE TITLE
Electrodes segmented outside skull

### ISSUE THREAD

**Issue by azian19360** [mnarizzano/SEEGA#28]
Dear SEEGA crew,

My issue at the moment is that in most of my results after running CPE electrodes are placed outside the skull and far beyond the given the mark ups given in the fiducial list of that specific patient. 

We make use of Ad-Tech electrodes, not of the DIXI-electrodes as set in default mode. But I entered the correct data in the config.file. Still estimatedly 20% of the electrodes is not calculated correctly. What to do about this issue?

Regards, 
Zian

**Comment by mnarizzano** [comment]
Dear Zian,
thank you for using SEEGA.
Regarding the issue, we need to reproduce the bug, so can you provide us the volume 
you are having problem with?
Massimo

**Comment by gabri470** [comment]
Dear Zian, 

CPE reconstructs the number of contacts based on the model you selected in the drop-down menu. To this end, selecting a default electrode with say 18 contacts for a 12 or 15 contacts lead will result in the last contacts to be reconstructed outside the cerebral volume. Moreover in one of the latest releases, CPE suggests you the best model from the list of models you provided in the config file. It uses a target-to-entry distance criterium such as it selects the model that fits best for that distance. 

However, as Massimamo was saying the best possibility for us to reproduce the bug is to have your data.

Thanks again for your interest in our tools. 

All the best,

**Comment by azian19360** [comment]
Dear Massimamo and Gabriel,

Thank you for responding on such a short notice. You're so helpfull. 

Hereby I send you the link to my data. I've ran SEEGA on a MRI with the electrodes segmented in it. I know that SEEGA is developed for CT-scan, but the same problem appears also in CT-scans. 

But as I see in the comment of Gabriel, maybe I should try the latest release of CPE, maybe it makes use of a better algoritm. Nevertheless I would like to ask you to look into my data. 

https://zianahmed.stackstorage.com/s/4Fu06CzhrSkNcBD 

Regards, Zian

**Comment by azian19360** [comment]
Dear devs,

As you recommended I tried to fix my issue myself by updating SEEGA to the latest version. After running CPE, the result is still the same as the result before the update. I hope you have looked into my data in the mean time?

Kind regards

**Comment by mnarizzano** [comment]
Dear Zian,
sorry for the late replay.
We did not have time to check it until now.
Today I have tried to download the data but I could not do it.
Can you upload them again?
thank you
massimo

**Comment by azian19360** [comment]
Dear Massimo,

Excuse me, I think the link had already reached it's expiry date. 
Again: https://zianahmed.stackstorage.com/s/xKgoxMkWMzvPLVG 

Regards, Zian

**Comment by mnarizzano** [comment]
Dear Azian
I have tried the data that you sent me, but I could not reproduce your error.

Let me check If I have done it correctly.
I have loaded the volume MRI
I Loaded the fcsv file 
I just selected the G electrodes.
I have selected TP and cEP in the Contact point Estimator
Even with my electrode config (the default one) the result was pretty much  good ( I guess) 

Looking at your question and to your result I could not understand what is the problem:
1) is the problem the fact that many contacts are outside the skull? or
2) Is the problem the fact that CPE construct electrodes in the wrong position?

Let me know please.
best
Massimo

**Comment by azian19360** [comment]
Dear Massimo,

Thank you for your effort. My problem is indeed mainly that many contact are outside the skull and I don't know what to do about it. In the situation where I want to compare different patients, I have to many electrodes with contacts outside the skull. This way the precision is questionable and I want to try to increase the precision some how. 

Regards, Ahmed

**Comment by azian19360** [comment]
Reminder!

**Comment by mnarizzano** [comment]
Dear Zian,
I am very sorry for been so late.
I did not still have an answer (well I did not have enough time to check)
As soon as I can I will check it deeply.
Cheers
massimo

2018-02-20 19:13 GMT+01:00 azian19360 <notifications@github.com>:

**Comment by gabri470** [comment]
Dear @azian19360, 

sorry for the very late answer but I completely lost control of GitHub in the past few months (and for some reasons it stopped pushing notifications).

Are you still experiencing the same error? Did you find a solution to your problem or want me to take a look at it?

The link above is still working and I downloaded the files. I'll make some tests and get back asap

All the best,
