### ISSUE TITLE
Nothing is displayed in the combobox fiducial list

### ISSUE THREAD

**Issue by MarcosSoares10** [mnarizzano/SEEGA#30]
I am studying your loadable module for segmentation through fiducial marks.
Those Fiducial markers should be loaded and displayed by the module automatically, but that doesn't happen.
I am not really sure that the provided instructions in the original code is right or is enough for that.
Json file is reading correctly, but, nothing is added to the combobox.

       `self.segmentationCB = ctk.ctkCollapsibleButton()
        self.segmentationCB.text = "ContactPositionEstimator - Segmentation"
        self.segmentationCB.contentsLineWidth = 1
        self.layout.addWidget(self.segmentationCB)
        
        self.segmentationFL = qt.QFormLayout(self.segmentationCB)

        self.fiducialCBox = slicer.qMRMLNodeComboBox()
        self.fiducialCBox.nodeTypes = (("vtkMRMLMarkupsFiducialNode"), "")
        self.fiducialCBox.selectNodeUponCreation = False
        self.fiducialCBox.addEnabled = False
        self.fiducialCBox.removeEnabled = False
        self.fiducialCBox.noneEnabled = True
        self.fiducialCBox.setMRMLScene(slicer.mrmlScene)
        self.fiducialCBox.setToolTip("Select a fiducial list")
       
        self.segmentationFL.addRow("Fiducial List", self.fiducialCBox)
        
        self.fiducialCBox.connect('currentNodeChanged(bool)', self.onfiducialCBox)
        with open(slicer.modules.ContactPositionEstimatorInstance.electrodeTypesPath) as data_file:
            self.models = json.load(data_file)

        self.tableCaption = ["Name", "Type/Model", "TP", "cEP"]
        self.tableHsize = [80, 180, 50, 50]
        self.captionGB = qt.QGroupBox(self.segmentationCB)
        self.captionBL = qt.QHBoxLayout(self.captionGB)
        self.captionBL.setMargin(1)
        for i in (xrange(len(self.tableCaption))):
            a = qt.QLabel(self.tableCaption[i], self.captionGB)
            a.setMaximumWidth(self.tableHsize[i])
            a.setMaximumHeight(20)
            a.setStyleSheet("qproperty-alignment: AlignCenter;")
            self.captionBL.addWidget(a)

        self.segmentationFL.addRow("", self.captionGB)
        self.electrodeList = []

`

**Comment by mnarizzano** [comment]
Dear Marcos,
could you please add mode details?
The last time I have checked everything was fine
mn

Il giorno ven 23 nov 2018 alle ore 03:54 MarcosSoares10 <
notifications@github.com> ha scritto:

**Comment by MarcosSoares10** [comment]
Dear, mnarizzano.
Which details stay better for do you see?
I don't understand because your algorithm, in specific, ContactPositionEstimator not load models in 

`self.fiducialCBox = slicer.qMRMLNodeComboBox()` 
this always is "None", if you activate the function 
`self.fiducialCBox.connect('currentNodeChanged(bool)', self.onfiducialCBox)`,
 the function not execute. She stops in 
` if self.fiducialCBox.currentNode() is None:
            return` 
because there isn't values into `self.fiducialCBox` 
I verified if the function 
`with open(slicer.modules.ContactPositionEstimatorInstance.electrodeTypesPath) as data_file:
        self.models = json.load(data_file)`
and she is executing normally, but fields of area 

> ContactPositionEstimator - Segmentation 

stay empty.

I need to specify markup points and set name of entry and target points to have something in fiducial list combobox?

I could send email with screenshoots about this to you.

Thank you.

**Comment by mnarizzano** [comment]
Well,
On my PC, the last time I have checked  it was working properly.
So in order to better understand the problem I need information to
replicate
the "possible" problem.
To sum up I need to know :
1) Operating System used
2) The version of 3D slicer
3) The python version
4) A sequence of steps you have performed to obtain the wrong behavior
5) Possible the data used or at least the types of data you have used.

Screenshoots can help.

Best
Massimo

Il giorno ven 23 nov 2018 alle ore 12:34 MarcosSoares10 <
notifications@github.com> ha scritto:

**Comment by MarcosSoares10** [comment]
1) My system is Linux Mint 18 64bits
2) Slicer 4.8
3) Python 2.7
4) I used your sequence to add module in slicer:
Change line in the file "deeto.config" to linux, after open slicer, and,
Button edit>applications settings>modules>add>ok
After this restart automatically slicer and i look window from your module show-me "None" in  fiduciallist (ContactPositionEstimator - Configuration ComboBox) and there are others values.
5) In this moment, i only install your module and try understand the visual of interface, then, i look this possible problem. 

A screenshoot is demonstred in link below.
[Screenshoot](https://drive.google.com/open?id=1XGWP_jctXq9Fod4nUxbq8AYm5zTUaWsi)

From what I understand markups should already load automatically.
I was reading and studying your paper. 

Thank you
Marcos.

**Comment by mnarizzano** [comment]
Sorry from your screenshot and from the procedure you described I could not
understand if you follows this instruction,
https://github.com/mnarizzano/SEEGA/tree/master/ContactPositionEstimator#32-deeto---segmentation
In particular the 3.2 section.
If you follow the instruction, then please send me the data (CT volume and
the markup fiducial file).
and I will try to replicate your problem,
mn

**Comment by gabri470** [comment]
Dear @MarcosSoares10, 

> I need to specify markup points and set name of entry and target points to have something in fiducial list combobox?

Yes you need to specify cortical entry (cEP) and target (TP) points. This is achieved using markups module in 3DSlicer and defining two points for each electrode shaft. You should mark the two points with the same capital letter. 

let us know whether you still encounters any issue.

**Comment by MarcosSoares10** [comment]
Great! Thank you.

I will try creating several manually and send results here. 

I created 2 markups and executed segmentation test, but had problems at the module "BrazinZoneDetector", maybe caused by some problem  in "ContactPositionEstimator" results.

Other thing, there isn't the path/file  "SEEGA/DEETO/DEETO.py" in this module, described in [here](https://github.com/mnarizzano/SEEGA/tree/master/ContactPositionEstimator#32-deeto---segmentation) by@mnarizzano in this module.

I will try again.

**Comment by gabri470** [comment]
You can also specify markups in a fiducial file expressed in csv format with label in first column, and x,y,z triplets in the following.

Thanks for pointing out that error in documentation.

**Comment by MarcosSoares10** [comment]
This are my steps and screenshots.

1: Create Markups with Module "Markups" [Screeshoot](https://drive.google.com/file/d/1s4ZAgDfeEENAlSdA0H1XVupAs0wUYJ1P/view?usp=sharing)

2: I used this markups in "ContactPositionEstimator" and results [Screenshot](https://drive.google.com/file/d/1e19zNjVEPuBqvbBgXy2-v1DxDwT8FctL/view?usp=sharing) 

3: I try execute "BrainZoneDetector" and crash ([Screenshoot](https://drive.google.com/file/d/1M1bQku_ho4a46XZKUm1MKdTbg-_Hv-H_/view?usp=sharing)), also, this is returned in terminal 

`RUN Zone Detection Algorithm
Traceback (most recent call last):
File "/home/marcos/SEEGA/BrainZoneDetector/BrainZoneDetector.py", line 129, in onZoneButton
    self.lutPath, int(self.ROISize.text),self.lutSelector.currentIndex)
 File "/home/marcos/SEEGA/BrainZoneDetector/BrainZoneDetector.py", line 243, in runZoneDetection
    patchNames = [re.sub('((ctx_.h_)|(Right|Left)-(Cerebral-)?)', '', FSLUT[pValues]) for pValues in uniqueValues]

KeyError: 178
`


My System Operational is Linux Mint 18 64bits
Slicer 4.8
Python 2.7

Thank you

**Comment by gabri470** [comment]
Dear @MarcosSoares10 

please carefully read the paper https://www.ncbi.nlm.nih.gov/pubmed/28231759 where you should find all relevant information to fully pursue your aims. 

There are several wrong steps you performed according to your screenshots. Listing the more evident:
1 - cortical entry point and target point should be placed near the real cortical and target points (while you placed them in _random_ position)
2 - CT post implant should be thresholded to reduce artefacts
2a- CT post should be skull stripped since skull voxels have intensities similar to contacts and this fact leads to erroneous estimation of the histogram
3 - Brain zone detector requires an atlas such as those provided by Freesurfer to correctly look for anatomical locations and not a CT scan (where by the way there is not visible brain as you can see)

Please carefully read the paper and get back if any problems. 

I am closing this issue because it's not a software issue. 

Thanks again for your interest in our tool. 

Best regards,
