### ISSUE TITLE
Modules not loaded error when trying to use after install

### ISSUE THREAD

**Issue by arge-7** [mnarizzano/SEEGA#36]
Hello, I just came across this very cool project yesterday and I'm trying to get started with it. I'm following the directions and add the folder paths to the four modules in Slicer as instructed. However, when I pull up my list of modules, they SEEGA ones all have error messages of not being loaded. The file structure of my other working modules seems different than those of the SEEGA modules, which all have lib and share folders containing all the contents. I'm running macOS Monterey and Slicer 5.1.0-2022-05-11. I'm probably missing something obvious but I would appreciate any input. I've attached screenshots of how I'm trying to install SEEGA and the error I'm seeing. Thanks!

<img width="1030" alt="Screen Shot 2022-05-13 at 9 36 57 AM" src="https://user-images.githubusercontent.com/68198440/168307948-1a99572b-25fd-487a-9377-637df4780c1f.png">

<img width="690" alt="Screen Shot 2022-05-13 at 9 37 29 AM" src="https://user-images.githubusercontent.com/68198440/168307954-5c872463-4d27-449f-be1b-6eac557dea9b.png">

**Comment by mosenco** [comment]
SEEGA was using Python2 while Slicer 5 is using Python3. Also when Slicer migrating from 4 to 5, they changed, moved and renamed functions so SEEGA wasn't working for the new Slicer.

But right now the porting of SEEGA for Slicer 5 is available!
